avList = {
	"360tray.exe": "360安全卫士-实时保护",
	"360safe.exe": "360安全卫士-主程序",
	"ZhuDongFangYu.exe": "360安全卫士-主动防御",
	"360sd.exe": "360杀毒",
	"a2guard.exe": "a-squared杀毒",
	"ad-watch.exe": "Lavasoft杀毒",
	"cleaner8.exe": "The Cleaner杀毒",
	"vba32lder.exe": "vb32杀毒",
	"MongoosaGUI.exe": "Mongoosa杀毒",
	"CorantiControlCenter32.exe": "Coranti2012杀毒",
	"F-PROT.exe": "F-Prot AntiVirus",
	"CMCTrayIcon.exe": "CMC杀毒",
	"K7TSecurity.exe": "K7杀毒",
	"UnThreat.exe": "UnThreat杀毒",
	"CKSoftShiedAntivirus4.exe": "Shield Antivirus杀毒",
	"AVWatchService.exe": "VIRUSfighter杀毒",
	"ArcaTasksService.exe": "ArcaVir杀毒",
	"iptray.exe": "Immunet杀毒",
	"PSafeSysTray.exe": "PSafe杀毒",
	"nspupsvc.exe": "nProtect杀毒",
	"SpywareTerminatorShield.exe": "SpywareTerminator反间谍软件",
	"BKavService.exe": "Bkav杀毒",
	"MsMpEng.exe": "Windows Defender",
	"SBAMSvc.exe": "VIPRE",
	"ccSvcHst.exe": "Norton杀毒",
	"f-secure.exe": "冰岛",
	"avp.exe": "Kaspersky",
	"KvMonXP.exe": "江民杀毒",
	"RavMonD.exe": "瑞星杀毒",
	"Mcshield.exe": "McAfee",
	"Tbmon.exe": "McAfee",
	"Frameworkservice.exe": "McAfee",
	"egui.exe": "ESET NOD32",
	"ekrn.exe": "ESET NOD32",
	"eguiProxy.exe": "ESET NOD32",
	"kxetray.exe": "金山毒霸",
	"knsdtray.exe": "可牛杀毒",
	"TMBMSRV.exe": "趋势杀毒",
	"avcenter.exe": "Avira(小红伞)",
	"avguard.exe": "Avira(小红伞)",
	"avgnt.exe": "Avira(小红伞)",
	"sched.exe": "Avira(小红伞)",
	"ashDisp.exe": "Avast网络安全",
	"rtvscan.exe": "诺顿杀毒",
	"ccapp.exe": "SymantecNorton",
	"NPFMntor.exe": "Norton杀毒软件",
	"ccSetMgr.exe": "赛门铁克",
	"ccRegVfy.exe": "Norton杀毒软件",
	"ksafe.exe": "金山卫士",
	"QQPCRTP.exe": "QQ电脑管家",
	"avgwdsvc.exe": "AVG杀毒",
	"QUHLPSVC.exe": "QUICK HEAL杀毒",
	"mssecess.exe": "微软杀毒",
	"SavProgress.exe": "Sophos杀毒",
	"SophosUI.exe": "Sophos杀毒",
	"SophosFS.exe": "Sophos杀毒",
	"SophosHealth.exe": "Sophos杀毒",
	"SophosSafestore64.exe": "Sophos杀毒",
	"SophosCleanM.exe": "Sophos杀毒",
	"fsavgui.exe": "F-Secure杀毒",
	"vsserv.exe": "比特梵德",
	"remupd.exe": "熊猫卫士",
	"FortiTray.exe": "飞塔",
	"safedog.exe": "安全狗",
	"parmor.exe": "木马克星",
	"Iparmor.exe.exe": "木马克星",
	"beikesan.exe": "贝壳云安全",
	"KSWebShield.exe": "金山网盾",
	"TrojanHunter.exe": "木马猎手",
	"GG.exe": "巨盾网游安全盾",
	"adam.exe": "绿鹰安全精灵",
	"AST.exe": "超级巡警",
	"ananwidget.exe": "墨者安全专家",
	"AVK.exe": "AntiVirusKit",
	"avg.exe": "AVG Anti-Virus",
	"spidernt.exe": "Dr.web",
	"avgaurd.exe": "Avira Antivir",
	"vsmon.exe": "Zone Alarm",
	"cpf.exe": "Comodo",
	"outpost.exe": "Outpost Firewall",
	"rfwmain.exe": "瑞星防火墙",
	"kpfwtray.exe": "金山网镖",
	"FYFireWall.exe": "风云防火墙",
	"MPMon.exe": "微点主动防御",
	"pfw.exe": "天网防火墙",
	"BaiduSdSvc.exe": "百度杀毒-服务进程",
	"BaiduSdTray.exe": "百度杀毒-托盘进程",
	"BaiduSd.exe": "百度杀毒-主程序",
	"SafeDogGuardCenter.exe": "安全狗",
	"safedogupdatecenter.exe": "安全狗",
	"safedogguardcenter.exe": "安全狗",
	"SafeDogSiteIIS.exe": "安全狗",
	"SafeDogTray.exe": "安全狗",
	"SafeDogServerUI.exe": "安全狗",
	"D_Safe_Manage.exe": "D盾",
	"d_manage.exe": "D盾",
	"yunsuo_agent_service.exe": "云锁",
	"yunsuo_agent_daemon.exe": "云锁",
	"HwsPanel.exe": "护卫神",
	"hws_ui.exe": "护卫神",
	"hws.exe": "护卫神",
	"hwsd.exe": "护卫神",
	"HipsTray.exe": "火绒",
	"HipsDaemon.exe": "火绒",
	"wsctrl.exe": "火绒",
	"usysdiag.exe": "火绒",
	"SPHINX.exe": "SPHINX防火墙",
	"bddownloader.exe": "百度卫士",
	"baiduansvx.exe": "百度卫士-主进程",
	"AvastUI.exe": "Avast!5主程序",
	"emet_agent.exe": "EMET",
	"emet_service.exe": "EMET",
	"firesvc.exe": "McAfee",
	"firetray.exe": "McAfee",
	"hipsvc.exe": "McAfee",
	"mfevtps.exe": "McAfee",
	"mcafeefire.exe": "McAfee",
	"scan32.exe": "McAfee",
	"shstat.exe": "McAfee",
	"vstskmgr.exe": "McAfee",
	"engineserver.exe": "McAfee",
	"mfeann.exe": "McAfee",
	"mcscript.exe": "McAfee",
	"updaterui.exe": "McAfee",
	"udaterui.exe": "McAfee",
	"naprdmgr.exe": "McAfee",
	"cleanup.exe": "McAfee",
	"cmdagent.exe": "McAfee",
	"frminst.exe": "McAfee",
	"mcscript_inuse.exe": "McAfee",
	"mctray.exe": "McAfee",
	"_avp32.exe": "卡巴斯基",
	"_avpcc.exe": "卡巴斯基",
	"_avpm.exe": "卡巴斯基",
	"aAvgApi.exe": "AVG",
	"ackwin32.exe": "已知杀软进程,名称暂未收录",
	"alertsvc.exe": "Norton AntiVirus",
	"alogserv.exe": "McAfee VirusScan",
	"anti-trojan.exe": "Anti-Trojan Elite",
	"arr.exe": "Application Request Route",
	"atguard.exe": "AntiVir",
	"atupdater.exe": "已知杀软进程,名称暂未收录",
	"atwatch.exe": "Mustek",
	"au.exe": "NSIS",
	"aupdate.exe": "Symantec",
	"auto-protect.nav80try.exe": "已知杀软进程,名称暂未收录",
	"autodown.exe": "AntiVirus AutoUpdater",
	"avconsol.exe": "McAfee",
	"avgcc32.exe": "AVG",
	"avgctrl.exe": "AVG",
	"avgemc.exe": "AVG",
	"avgrsx.exe": "AVG",
	"avgserv.exe": "AVG",
	"avgserv9.exe": "AVG",
	"avgw.exe": "AVG",
	"avkpop.exe": "G DATA SOFTWARE AG",
	"avkserv.exe": "G DATA SOFTWARE AG",
	"avkservice.exe": "G DATA SOFTWARE AG",
	"avkwctl9.exe": "G DATA SOFTWARE AG",
	"avltmain.exe": "Panda Software Aplication",
	"avnt.exe": "H+BEDV Datentechnik GmbH",
	"avp32.exe": "Kaspersky Anti-Virus",
	"avpcc.exe": " Kaspersky AntiVirus",
	"avpdos32.exe": " Kaspersky AntiVirus",
	"avpm.exe": " Kaspersky AntiVirus",
	"avptc32.exe": " Kaspersky AntiVirus",
	"avpupd.exe": " Kaspersky AntiVirus",
	"avsynmgr.exe": "McAfee",
	"avwin.exe": " H+BEDV",
	"bargains.exe": "Exact Advertising SpyWare",
	"beagle.exe": "Avast",
	"blackd.exe": "BlackICE",
	"blackice.exe": "BlackICE",
	"blink.exe": "micromedia",
	"blss.exe": "CBlaster",
	"bootwarn.exe": "Symantec",
	"bpc.exe": "Grokster",
	"brasil.exe": "Exact Advertising",
	"ccevtmgr.exe": "Norton Internet Security",
	"cdp.exe": "CyberLink Corp.",
	"cfd.exe": "Motive Communications",
	"cfgwiz.exe": " Norton AntiVirus",
	"claw95.exe": "已知杀软进程,名称暂未收录",
	"claw95cf.exe": "已知杀软进程,名称暂未收录",
	"clean.exe": "windows流氓软件清理大师",
	"cleaner.exe": "windows流氓软件清理大师",
	"cleaner3.exe": "windows流氓软件清理大师",
	"cleanpc.exe": "windows流氓软件清理大师",
	"cpd.exe": "McAfee",
	"ctrl.exe": "已知杀软进程,名称暂未收录",
	"cv.exe": "已知杀软进程,名称暂未收录",
	"defalert.exe": "Symantec",
	"defscangui.exe": "Symantec",
	"defwatch.exe": "Norton Antivirus",
	"doors.exe": "已知杀软进程,名称暂未收录",
	"dpf.exe": "已知杀软进程,名称暂未收录",
	"dpps2.exe": "PanicWare",
	"dssagent.exe": "Broderbund",
	"ecengine.exe": "已知杀软进程,名称暂未收录",
	"emsw.exe": "Alset Inc",
	"ent.exe": "已知杀软进程,名称暂未收录",
	"espwatch.exe": "已知杀软进程,名称暂未收录",
	"ethereal.exe": "RationalClearCase",
	"exe.avxw.exe": "已知杀软进程,名称暂未收录",
	"expert.exe": "已知杀软进程,名称暂未收录",
	"f-prot95.exe": "已知杀软进程,名称暂未收录",
	"fameh32.exe": "F-Secure",
	"fast.exe": " FastUsr",
	"fch32.exe": "F-Secure",
	"fih32.exe": "F-Secure",
	"findviru.exe": "F-Secure",
	"firewall.exe": "AshampooSoftware",
	"fnrb32.exe": "F-Secure",
	"fp-win.exe": " F-Prot Antivirus OnDemand",
	"fsaa.exe": "F-Secure",
	"fsav.exe": "F-Secure",
	"fsav32.exe": "F-Secure",
	"fsav530stbyb.exe": "F-Secure",
	"fsav530wtbyb.exe": "F-Secure",
	"fsav95.exe": "F-Secure",
	"fsgk32.exe": "F-Secure",
	"fsm32.exe": "F-Secure",
	"fsma32.exe": "F-Secure",
	"fsmb32.exe": "F-Secure",
	"gbmenu.exe": "已知杀软进程,名称暂未收录",
	"guard.exe": "ewido",
	"guarddog.exe": "ewido",
	"htlog.exe": "已知杀软进程,名称暂未收录",
	"htpatch.exe": "Silicon Integrated Systems Corporation",
	"hwpe.exe": "已知杀软进程,名称暂未收录",
	"iamapp.exe": "Symantec",
	"iamserv.exe": "Symantec",
	"iamstats.exe": "Symantec",
	"iedriver.exe": " Urlblaze.com",
	"iface.exe": "Panda Antivirus Module",
	"infus.exe": "Infus Dialer",
	"infwin.exe": "Msviewparasite",
	"intdel.exe": "Inet Delivery",
	"intren.exe": "已知杀软进程,名称暂未收录",
	"jammer.exe": "已知杀软进程,名称暂未收录",
	"kavpf.exe": "Kapersky",
	"kazza.exe": "Kapersky",
	"keenvalue.exe": "EUNIVERSE INC",
	"launcher.exe": "Intercort Systems",
	"ldpro.exe": "已知杀软进程,名称暂未收录",
	"ldscan.exe": "Windows Trojans Inspector",
	"localnet.exe": "已知杀软进程,名称暂未收录",
	"luall.exe": "Symantec",
	"luau.exe": "Symantec",
	"lucomserver.exe": "Norton",
	"mcagent.exe": "McAfee",
	"mcmnhdlr.exe": "McAfee",
	"mctool.exe": "McAfee",
	"mcupdate.exe": "McAfee",
	"mcvsrte.exe": "McAfee",
	"mcvsshld.exe": "McAfee",
	"mfin32.exe": "MyFreeInternetUpdate",
	"mfw2en.exe": "MyFreeInternetUpdate",
	"mfweng3.02d30.exe": "MyFreeInternetUpdate",
	"mgavrtcl.exe": "McAfee",
	"mgavrte.exe": "McAfee",
	"mghtml.exe": "McAfee",
	"mgui.exe": "BullGuard",
	"minilog.exe": "Zone Labs Inc",
	"mmod.exe": "EzulaInc",
	"mostat.exe": "WurldMediaInc",
	"mpfagent.exe": "McAfee",
	"mpfservice.exe": "McAfee",
	"mpftray.exe": "McAfee",
	"mscache.exe": "Integrated Search Technologies Spyware",
	"mscman.exe": "OdysseusMarketingInc",
	"msmgt.exe": "Total Velocity Spyware",
	"msvxd.exe": "W32/Datom-A",
	"mwatch.exe": "已知杀软进程,名称暂未收录",
	"nav.exe": "Reuters Limited",
	"navapsvc.exe": "Norton AntiVirus",
	"navapw32.exe": "Norton AntiVirus",
	"navw32.exe": "Norton Antivirus",
	"ndd32.exe": "诺顿磁盘医生",
	"neowatchlog.exe": "已知杀软进程,名称暂未收录",
	"netutils.exe": "已知杀软进程,名称暂未收录",
	"nisserv.exe": "Norton",
	"nisum.exe": "Norton",
	"nmain.exe": "Norton",
	"nod32.exe": "ESET Smart Security",
	"norton_internet_secu_3.0_407.exe": "已知杀软进程,名称暂未收录",
	"notstart.exe": "已知杀软进程,名称暂未收录",
	"nprotect.exe": "Symantec",
	"npscheck.exe": "Norton",
	"npssvc.exe": "Norton",
	"ntrtscan.exe": "趋势反病毒应用程序",
	"nui.exe": "已知杀软进程,名称暂未收录",
	"otfix.exe": "已知杀软进程,名称暂未收录",
	"outpostinstall.exe": "Outpost",
	"patch.exe": "趋势科技",
	"pavw.exe": "已知杀软进程,名称暂未收录",
	"pcscan.exe": "趋势科技",
	"pdsetup.exe": "已知杀软进程,名称暂未收录",
	"persfw.exe": "Tiny Personal Firewall",
	"pgmonitr.exe": "PromulGate SpyWare",
	"pingscan.exe": "已知杀软进程,名称暂未收录",
	"platin.exe": "已知杀软进程,名称暂未收录",
	"pop3trap.exe": "PC-cillin",
	"poproxy.exe": "NortonAntiVirus",
	"popscan.exe": "已知杀软进程,名称暂未收录",
	"powerscan.exe": "Integrated Search Technologies",
	"ppinupdt.exe": "已知杀软进程,名称暂未收录",
	"pptbc.exe": "已知杀软进程,名称暂未收录",
	"ppvstop.exe": "已知杀软进程,名称暂未收录",
	"prizesurfer.exe": "Prizesurfer",
	"prmt.exe": "OpiStat",
	"prmvr.exe": "Adtomi",
	"processmonitor.exe": "Sysinternals",
	"proport.exe": "已知杀软进程,名称暂未收录",
	"protectx.exe": "ProtectX",
	"pspf.exe": "已知杀软进程,名称暂未收录",
	"purge.exe": "已知杀软进程,名称暂未收录",
	"qconsole.exe": "Norton AntiVirus Quarantine Console",
	"qserver.exe": "Norton Internet Security",
	"rapapp.exe": "BlackICE",
	"rb32.exe": "RapidBlaster",
	"rcsync.exe": "PrizeSurfer",
	"realmon.exe": "Realmon ",
	"rescue.exe": "已知杀软进程,名称暂未收录",
	"rescue32.exe": "卡巴斯基互联网安全套装",
	"rshell.exe": "已知杀软进程,名称暂未收录",
	"rtvscn95.exe": "Real-time virus scanner ",
	"rulaunch.exe": "McAfee User Interface",
	"run32dll.exe": "PAL PC Spy",
	"safeweb.exe": "PSafe Tecnologia",
	"sbserv.exe": "Norton Antivirus",
	"scrscan.exe": "360杀毒",
	"sfc.exe": "System file checker",
	"sh.exe": "MKS Toolkit for Win3",
	"showbehind.exe": "MicroSmarts Enterprise Component ",
	"soap.exe": "System Soap Pro",
	"sofi.exe": "已知杀软进程,名称暂未收录",
	"sperm.exe": "已知杀软进程,名称暂未收录",
	"supporter5.exe": "eScorcher反病毒",
	"symproxysvc.exe": "Symantec",
	"symtray.exe": "Symantec",
	"tbscan.exe": "ThunderBYTE",
	"tc.exe": "TimeCalende",
	"titanin.exe": "TitanHide",
	"tvmd.exe": "Total Velocity",
	"tvtmd.exe": " Total Velocity",
	"vettray.exe": "eTrust",
	"vir-help.exe": "已知杀软进程,名称暂未收录",
	"vnpc3000.exe": "已知杀软进程,名称暂未收录",
	"vpc32.exe": "Symantec",
	"vpc42.exe": "Symantec",
	"vshwin32.exe": "McAfee",
	"vsmain.exe": "McAfee",
	"vsstat.exe": "McAfee",
	"wfindv32.exe": "已知杀软进程,名称暂未收录",
	"zapro.exe": "Zone Alarm",
	"zonealarm.exe": "Zone Alarm",
	"AVPM.exe": "Kaspersky",
	"A2CMD.exe": "Emsisoft Anti-Malware",
	"A2SERVICE.exe": "a-squared free",
	"A2FREE.exe": "a-squared Free",
	"ADVCHK.exe": "Norton AntiVirus",
	"AGB.exe": "安天防线",
	"AHPROCMONSERVER.exe": "安天防线",
	"AIRDEFENSE.exe": "AirDefense",
	"ALERTSVC.exe": "Norton AntiVirus",
	"AVIRA.exe": "小红伞杀毒",
	"AMON.exe": "Tiny Personal Firewall",
	"AVZ.exe": "AVZ",
	"ANTIVIR.exe": "已知杀软进程,名称暂未收录",
	"APVXDWIN.exe": "熊猫卫士",
	"ASHMAISV.exe": "Alwil",
	"ASHSERV.exe": "Avast Anti-virus",
	"ASHSIMPL.exe": "AVAST!VirusCleaner",
	"ASHWEBSV.exe": "Avast",
	"ASWUPDSV.exe": "Avast",
	"ASWSCAN.exe": "Avast",
	"AVCIMAN.exe": "熊猫卫士",
	"AVCONSOL.exe": "McAfee",
	"AVENGINE.exe": "熊猫卫士",
	"AVESVC.exe": "Avira AntiVir Security Service",
	"AVEVL32.exe": "已知杀软进程,名称暂未收录",
	"AVGAM.exe": "AVG",
	"AVGCC.exe": "AVG",
	"AVGCHSVX.exe": "AVG",
	"AVGCSRVX": "AVG",
	"AVGNSX.exe": "AVG",
	"AVGCC32.exe": "AVG",
	"AVGCTRL.exe": "AVG",
	"AVGEMC.exe": "AVG",
	"AVGFWSRV.exe": "AVG",
	"AVGNTMGR.exe": "AVG",
	"AVGSERV.exe": "AVG",
	"AVGTRAY.exe": "AVG",
	"AVGUPSVC.exe": "AVG",
	"AVINITNT.exe": "Command AntiVirus for NT Server",
	"AVPCC.exe": "Kaspersky",
	"AVSERVER.exe": "Kerio MailServer",
	"AVSCHED32.exe": "H+BEDV",
	"AVSYNMGR.exe": "McAfee",
	"AVWUPSRV.exe": "H+BEDV",
	"BDSWITCH.exe": "BitDefender Module",
	"BLACKD.exe": "BlackICE",
	"CCEVTMGR.exe": "Symantec",
	"CFP.exe": "COMODO",
	"CLAMWIN.exe": "ClamWin Portable",
	"CUREIT.exe": "DrWeb CureIT",
	"DEFWATCH.exe": "Norton Antivirus",
	"DRWADINS.exe": "Dr.Web",
	"DRWEB.exe": "Dr.Web",
	"DEFENDERDAEMON.exe": "ShadowDefender",
	"EWIDOCTRL.exe": "Ewido Security Suite",
	"EZANTIVIRUSREGISTRATIONCHECK.exe": "e-Trust Antivirus",
	"FIREWALL.exe": "AshampooSoftware",
	"FPROTTRAY.exe": "F-PROT Antivirus",
	"FPWIN.exe": "Verizon",
	"FRESHCLAM.exe": "ClamAV",
	"FSAV32.exe": "F-Secure",
	"FSBWSYS.exe": "F-secure",
	"FSDFWD.exe": "F-Secure",
	"FSGK32.exe": "F-Secure",
	"FSGK32ST.exe": "F-Secure",
	"FSMA32.exe": "F-Secure",
	"FSMB32.exe": "F-Secure",
	"FSSM32.exe": "F-Secure",
	"GUARDGUI.exe": "网游保镖",
	"GUARDNT.exe": "IKARUS",
	"IAMAPP.exe": "Symantec",
	"INOCIT.exe": "eTrust",
	"INORPC.exe": "eTrust",
	"INORT.exe": "eTrust",
	"INOTASK.exe": "eTrust",
	"INOUPTNG.exe": "eTrust",
	"ISAFE.exe": "eTrust",
	"KAV.exe": "Kaspersky",
	"KAVMM.exe": "Kaspersky",
	"KAVPF.exe": "Kaspersky",
	"KAVPFW.exe": "Kaspersky",
	"KAVSTART.exe": "Kaspersky",
	"KAVSVC.exe": "Kaspersky",
	"KAVSVCUI.exe": "Kaspersky",
	"KMAILMON.exe": "金山毒霸",
	"MCAGENT.exe": "McAfee",
	"MCMNHDLR.exe": "McAfee",
	"MCREGWIZ.exe": "McAfee",
	"MCUPDATE.exe": "McAfee",
	"MCVSSHLD.exe": "McAfee",
	"MINILOG.exe": "Zone Alarm",
	"MYAGTSVC.exe": "McAfee",
	"MYAGTTRY.exe": "McAfee",
	"NAVAPSVC.exe": "Norton",
	"NAVAPW32.exe": "Norton",
	"NAVLU32.exe": "Norton",
	"NAVW32.exe": "Norton Antivirus",
	"NEOWATCHLOG.exe": "NeoWatch",
	"NEOWATCHTRAY.exe": "NeoWatch",
	"NISSERV.exe": "Norton",
	"NISUM.exe": "Norton",
	"NMAIN.exe": "Norton",
	"NOD32.exe": "ESET NOD32",
	"NPFMSG.exe": "Norman个人防火墙",
	"NPROTECT.exe": "Symantec",
	"NSMDTR.exe": "Norton",
	"NTRTSCAN.exe": "趋势科技",
	"OFCPFWSVC.exe": "OfficeScanNT",
	"ONLINENT.exe": "已知杀软进程,名称暂未收录",
	"OP_MON.exe": " OutpostFirewall",
	"PAVFIRES.exe": "熊猫卫士",
	"PAVFNSVR.exe": "熊猫卫士",
	"PAVKRE.exe": "熊猫卫士",
	"PAVPROT.exe": "熊猫卫士",
	"PAVPROXY.exe": "熊猫卫士",
	"PAVPRSRV.exe": "熊猫卫士",
	"PAVSRV51.exe": "熊猫卫士",
	"PAVSS.exe": "熊猫卫士",
	"PCCGUIDE.exe": "PC-cillin",
	"PCCIOMON.exe": "PC-cillin",
	"PCCNTMON.exe": "PC-cillin",
	"PCCPFW.exe": "趋势科技",
	"PCCTLCOM.exe": "趋势科技",
	"PCTAV.exe": "PC Tools AntiVirus",
	"PERSFW.exe": "Tiny Personal Firewall",
	"PERVAC.exe": "已知杀软进程,名称暂未收录",
	"PESTPATROL.exe": "Ikarus",
	"PREVSRV.exe": "熊猫卫士",
	"RTVSCN95.exe": "Real-time Virus Scanner",
	"SAVADMINSERVICE.exe": "SAV",
	"SAVMAIN.exe": "SAV",
	"SAVSCAN.exe": "SAV",
	"SDHELP.exe": "Spyware Doctor",
	"SHSTAT.exe": "McAfee",
	"SPBBCSVC.exe": "Symantec",
	"SPIDERCPL.exe": "Dr.Web",
	"SPIDERML.exe": "Dr.Web",
	"SPIDERUI.exe": "Dr.Web",
	"SPYBOTSD.exe": "Spybot ",
	"SWAGENT.exe": "SonicWALL",
	"SWDOCTOR.exe": "SonicWALL",
	"SWNETSUP.exe": "Sophos",
	"SYMLCSVC.exe": "Symantec",
	"SYMPROXYSVC.exe": "Symantec",
	"SYMSPORT.exe": "Sysmantec",
	"SYMWSC.exe": "Sysmantec",
	"SYNMGR.exe": "Sysmantec",
	"TMLISTEN.exe": "趋势科技",
	"TMNTSRV.exe": "趋势科技",
	"TMPROXY.exe": "趋势科技",
	"TNBUTIL.exe": "Anti-Virus",
	"VBA32ECM.exe": "已知杀软进程,名称暂未收录",
	"VBA32IFS.exe": "已知杀软进程,名称暂未收录",
	"VBA32PP3.exe": "已知杀软进程,名称暂未收录",
	"VCRMON.exe": "VirusChaser",
	"VRMONNT.exe": "HAURI",
	"VRMONSVC.exe": "HAURI",
	"VSHWIN32.exe": "McAfee",
	"VSSTAT.exe": "McAfee",
	"XCOMMSVR.exe": "BitDefender",
	"ZONEALARM.exe": "Zone Alarm",
	"360rp.exe": "360杀毒",
	"afwServ.exe": " Avast Antivirus ",
	"safeboxTray.exe": "360杀毒",
	"360safebox.exe": "360杀毒",
	"QQPCTray.exe": "QQ电脑管家",
	"KSafeTray.exe": "金山毒霸",
	"KSafeSvc.exe": "金山毒霸",
	"KWatch.exe": "金山毒霸",
	"gov_defence_service.exe": "云锁",
	"gov_defence_daemon.exe": "云锁",
	"smartscreen.exe": "Windows Defender",
	"macompatsvc.exe": "McAfee",
	"mcamnsvc.exe ": "McAfee",
	"masvc.exe": "McAfee",
	"mfemms.exe": "McAfee",
	"mctary.exe": "McAfee",
	"mcshield.exe": "McAfee",
	"mfewc.exe": "McAfee",
	"mfewch.exe": "McAfee",
	"mfefw.exe": "McAfee",
	"mfefire.exe": "McAfee",
	"mfetp.exe": "McAfee",
	"mfecanary.exe": "McAfee",
	"mfeconsole.exe": "McAfee",
	"mfeesp.exe": "McAfee",
	"fcag.exe": "McAfee",
	"fcags.exe": "McAfee",
	"fcagswd.exe": "McAfee",
	"fcagate.exe": "McAfee",
	"360EntClient.exe": "天擎EDR Agent",
	"edr_sec_plan.exe": "深信服EDR Agent",
	"edr_monitor.exe": "深信服EDR Agent",
	"edr_agent.exe": "深信服EDR Agent",
	"ESCCControl.exe": "启明星辰天珣EDR Agent",
	"ESCC.exe": "启明星辰天珣EDR Agent",
	"ESAV.exe": "启明星辰天珣EDR Agent",
	"ESCCIndex.exe": "启明星辰天珣EDR Agent",
	"AliYunDun.exe": "阿里云云盾",
	"wdswfsafe.exe": "360杀毒-网盾",
	"TopsecMain.exe": "天融信终端防御",
	"TopsecTray.exe": "天融信终端防御",
	"YDLive.exe":"腾讯云-云镜",
	"YDService.exe":"腾讯云-云镜",
	"TitanAgent.exe":"天眼云镜",
	"TitanMonitor.exe":"天眼云镜",
	"gse_win_daemon.exe":"蓝鲸Agent",
	"gse_win_agent.exe":"蓝鲸Agent",
	"vptray.exe": "Norton病毒防火墙-盾牌图标程序", 
	"Miner.exe": "流量矿石", 
	"AYAgent.exe": "韩国胶囊", 
	"patray.exe": "安博士", 
	"V3Svc.exe": "安博士V3", 
	"S.exe": "在抓鸡", 
	"1433.exe": "在扫1433", 
	"DUB.exe": "在爆破", 
	"ServUDaemon.exe": "发现S-U", 
	"WEBSCANX.exe": "网络病毒克星", 
	"AAWTray.exe": "已知杀软进程,名称暂未收录", 
	"Ad-Aware.exe": "已知杀软进程,名称暂未收录", 
	"MSASCui.exe": "已知杀软进程,名称暂未收录", 
	"adaware.exe": "已知杀软进程,名称暂未收录", 
	"advxdwin.exe": "已知杀软进程,名称暂未收录", 
	"agentsvr.exe": "已知杀软进程,名称暂未收录", 
	"agentw.exe": "已知杀软进程,名称暂未收录", 
	"alevir.exe": "已知杀软进程,名称暂未收录", 
	"amon9x.exe": "已知杀软进程,名称暂未收录", 
	"antivirus.exe": "已知杀软进程,名称暂未收录", 
	"ants.exe": "已知杀软进程,名称暂未收录", 
	"apimonitor.exe": "已知杀软进程,名称暂未收录", 
	"aplica32.exe": "已知杀软进程,名称暂未收录", 
	"atcon.exe": "已知杀软进程,名称暂未收录", 
	"atro55en.exe": "已知杀软进程,名称暂未收录", 
	"autotrace.exe": "已知杀软进程,名称暂未收录", 
	"autoupdate.exe": "已知杀软进程,名称暂未收录", 
	"ave32.exe": "已知杀软进程,名称暂未收录", 
	"avwin95.exe": "已知杀软进程,名称暂未收录", 
	"avwinnt.exe": "已知杀软进程,名称暂未收录", 
	"avwupd.exe": "已知杀软进程,名称暂未收录", 
	"avwupd32.exe": "已知杀软进程,名称暂未收录", 
	"avxmonitor9x.exe": "已知杀软进程,名称暂未收录", 
	"avxmonitornt.exe": "已知杀软进程,名称暂未收录", 
	"avxquar.exe": "已知杀软进程,名称暂未收录", 
	"backweb.exe": "已知杀软进程,名称暂未收录", 
	"bd_professional.exe": "已知杀软进程,名称暂未收录", 
	"belt.exe": "已知杀软进程,名称暂未收录", 
	"bidef.exe": "已知杀软进程,名称暂未收录", 
	"bidserver.exe": "已知杀软进程,名称暂未收录", 
	"bipcp.exe": "已知杀软进程,名称暂未收录", 
	"bipcpevalsetup.exe": "已知杀软进程,名称暂未收录", 
	"bisp.exe": "已知杀软进程,名称暂未收录", 
	"bootconf.exe": "已知杀软进程,名称暂未收录", 
	"borg2.exe": "已知杀软进程,名称暂未收录", 
	"bs120.exe": "已知杀软进程,名称暂未收录", 
	"bundle.exe": "已知杀软进程,名称暂未收录", 
	"bvt.exe": "已知杀软进程,名称暂未收录", 
	"ccpxysvc.exe": "已知杀软进程,名称暂未收录", 
	"cfiadmin.exe": "已知杀软进程,名称暂未收录", 
	"cfiaudit.exe": "已知杀软进程,名称暂未收录", 
	"cfinet.exe": "已知杀软进程,名称暂未收录", 
	"cfinet32.exe": "已知杀软进程,名称暂未收录", 
	"click.exe": "已知杀软进程,名称暂未收录", 
	"cmesys.exe": "已知杀软进程,名称暂未收录", 
	"cmgrdian.exe": "已知杀软进程,名称暂未收录", 
	"cmon016.exe": "已知杀软进程,名称暂未收录", 
	"connectionmonitor.exe": "已知杀软进程,名称暂未收录", 
	"cpf9x206.exe": "已知杀软进程,名称暂未收录", 
	"cpfnt206.exe": "已知杀软进程,名称暂未收录", 
	"cwnb181.exe": "已知杀软进程,名称暂未收录", 
	"cwntdwmo.exe": "已知杀软进程,名称暂未收录", 
	"datemanager.exe": "已知杀软进程,名称暂未收录", 
	"dcomx.exe": "已知杀软进程,名称暂未收录", 
	"deputy.exe": "已知杀软进程,名称暂未收录", 
	"divx.exe": "已知杀软进程,名称暂未收录", 
	"dllcache.exe": "已知杀软进程,名称暂未收录", 
	"dllreg.exe": "已知杀软进程,名称暂未收录", 
	"dpfsetup.exe": "已知杀软进程,名称暂未收录", 
	"drwatson.exe": "已知杀软进程,名称暂未收录", 
	"drweb32.exe": "已知杀软进程,名称暂未收录", 
	"drwebupw.exe": "已知杀软进程,名称暂未收录", 
	"dvp95.exe": "已知杀软进程,名称暂未收录", 
	"dvp95_0.exe": "已知杀软进程,名称暂未收录", 
	"efpeadm.exe": "已知杀软进程,名称暂未收录", 
	"esafe.exe": "已知杀软进程,名称暂未收录", 
	"escanhnt.exe": "已知杀软进程,名称暂未收录", 
	"escanv95.exe": "已知杀软进程,名称暂未收录", 
	"etrustcipe.exe": "已知杀软进程,名称暂未收录", 
	"evpn.exe": "已知杀软进程,名称暂未收录", 
	"exantivirus-cnet.exe": "已知杀软进程,名称暂未收录", 
	"explore.exe": "已知杀软进程,名称暂未收录", 
	"f-agnt95.exe": "已知杀软进程,名称暂未收录", 
	"f-stopw.exe": "已知杀软进程,名称暂未收录", 
	"fp-win_trial.exe": "已知杀软进程,名称暂未收录", 
	"fprot.exe": "已知杀软进程,名称暂未收录", 
	"frw.exe": "已知杀软进程,名称暂未收录", 
	"gator.exe": "已知杀软进程,名称暂未收录", 
	"gbpoll.exe": "已知杀软进程,名称暂未收录", 
	"generics.exe": "已知杀软进程,名称暂未收录", 
	"gmt.exe": "已知杀软进程,名称暂未收录", 
	"hacktracersetup.exe": "已知杀软进程,名称暂未收录", 
	"hbinst.exe": "已知杀软进程,名称暂未收录", 
	"hbsrv.exe": "已知杀软进程,名称暂未收录", 
	"hotactio.exe": "已知杀软进程,名称暂未收录", 
	"hotpatch.exe": "已知杀软进程,名称暂未收录", 
	"hxdl.exe": "已知杀软进程,名称暂未收录", 
	"hxiul.exe": "已知杀软进程,名称暂未收录", 
	"ibmasn.exe": "已知杀软进程,名称暂未收录", 
	"ibmavsp.exe": "已知杀软进程,名称暂未收录", 
	"icload95.exe": "已知杀软进程,名称暂未收录", 
	"icloadnt.exe": "已知杀软进程,名称暂未收录", 
	"icmon.exe": "已知杀软进程,名称暂未收录", 
	"icsupp95.exe": "已知杀软进程,名称暂未收录", 
	"icsuppnt.exe": "已知杀软进程,名称暂未收录", 
	"idle.exe": "已知杀软进程,名称暂未收录", 
	"iedll.exe": "已知杀软进程,名称暂未收录", 
	"ifw2000.exe": "已知杀软进程,名称暂未收录", 
	"inetlnfo.exe": "已知杀软进程,名称暂未收录", 
	"init.exe": "已知杀软进程,名称暂未收录", 
	"iomon98.exe": "已知杀软进程,名称暂未收录", 
	"istsvc.exe": "已知杀软进程,名称暂未收录", 
	"jdbgmrg.exe": "已知杀软进程,名称暂未收录", 
	"jedi.exe": "已知杀软进程,名称暂未收录", 
	"kavlite40eng.exe": "已知杀软进程,名称暂未收录", 
	"kavpers40eng.exe": "已知杀软进程,名称暂未收录", 
	"kerio-pf-213-en-win.exe": "已知杀软进程,名称暂未收录", 
	"kerio-wrl-421-en-win.exe": "已知杀软进程,名称暂未收录", 
	"kerio-wrp-421-en-win.exe": "已知杀软进程,名称暂未收录", 
	"kernel32.exe": "已知杀软进程,名称暂未收录", 
	"killprocesssetup161.exe": "已知杀软进程,名称暂未收录", 
	"ldnetmon.exe": "已知杀软进程,名称暂未收录", 
	"ldpromenu.exe": "已知杀软进程,名称暂未收录", 
	"lnetinfo.exe": "已知杀软进程,名称暂未收录", 
	"loader.exe": "已知杀软进程,名称暂未收录", 
	"lockdown.exe": "已知杀软进程,名称暂未收录", 
	"lockdown2000.exe": "已知杀软进程,名称暂未收录", 
	"lookout.exe": "已知杀软进程,名称暂未收录", 
	"lordpe.exe": "已知杀软进程,名称暂未收录", 
	"lsetup.exe": "已知杀软进程,名称暂未收录", 
	"luinit.exe": "已知杀软进程,名称暂未收录", 
	"luspt.exe": "已知杀软进程,名称暂未收录", 
	"mapisvc32.exe": "已知杀软进程,名称暂未收录", 
	"md.exe": "已知杀软进程,名称暂未收录", 
	"monitor.exe": "已知杀软进程,名称暂未收录", 
	"moolive.exe": "已知杀软进程,名称暂未收录", 
	"mrflux.exe": "已知杀软进程,名称暂未收录", 
	"msapp.exe": "已知杀软进程,名称暂未收录", 
	"msbb.exe": "已知杀软进程,名称暂未收录", 
	"msblast.exe": "已知杀软进程,名称暂未收录", 
	"msccn32.exe": "已知杀软进程,名称暂未收录", 
	"msconfig.exe": "已知杀软进程,名称暂未收录", 
	"msdm.exe": "已知杀软进程,名称暂未收录", 
	"msdos.exe": "已知杀软进程,名称暂未收录", 
	"msiexec16.exe": "已知杀软进程,名称暂未收录", 
	"msinfo32.exe": "已知杀软进程,名称暂未收录", 
	"mslaugh.exe": "已知杀软进程,名称暂未收录", 
	"msmsgri32.exe": "已知杀软进程,名称暂未收录", 
	"mssmmc32.exe": "已知杀软进程,名称暂未收录", 
	"mssys.exe": "已知杀软进程,名称暂未收录", 
	"mu0311ad.exe": "已知杀软进程,名称暂未收录", 
	"n32scanw.exe": "已知杀软进程,名称暂未收录", 
	"navap.navapsvc.exe": "已知杀软进程,名称暂未收录", 
	"navdx.exe": "已知杀软进程,名称暂未收录", 
	"navnt.exe": "已知杀软进程,名称暂未收录", 
	"navstub.exe": "已知杀软进程,名称暂未收录", 
	"navwnt.exe": "已知杀软进程,名称暂未收录", 
	"nc2000.exe": "已知杀软进程,名称暂未收录", 
	"ncinst4.exe": "已知杀软进程,名称暂未收录", 
	"neomonitor.exe": "已知杀软进程,名称暂未收录", 
	"netarmor.exe": "已知杀软进程,名称暂未收录", 
	"netd32.exe": "已知杀软进程,名称暂未收录", 
	"netinfo.exe": "已知杀软进程,名称暂未收录", 
	"netmon.exe": "已知杀软进程,名称暂未收录", 
	"netscanpro.exe": "已知杀软进程,名称暂未收录", 
	"netspyhunter-1.2.exe": "已知杀软进程,名称暂未收录", 
	"netstat.exe": "已知杀软进程,名称暂未收录", 
	"normist.exe": "已知杀软进程,名称暂未收录", 
	"npf40_tw_98_nt_me_2k.exe": "已知杀软进程,名称暂未收录", 
	"npfmessenger.exe": "已知杀软进程,名称暂未收录", 
	"nsched32.exe": "已知杀软进程,名称暂未收录", 
	"nssys32.exe": "已知杀软进程,名称暂未收录", 
	"nstask32.exe": "已知杀软进程,名称暂未收录", 
	"nsupdate.exe": "已知杀软进程,名称暂未收录", 
	"nt.exe": "已知杀软进程,名称暂未收录", 
	"ntvdm.exe": "已知杀软进程,名称暂未收录", 
	"ntxconfig.exe": "已知杀软进程,名称暂未收录", 
	"nupgrade.exe": "已知杀软进程,名称暂未收录", 
	"nvarch16.exe": "已知杀软进程,名称暂未收录", 
	"nvc95.exe": "已知杀软进程,名称暂未收录", 
	"nvsvc32.exe": "已知杀软进程,名称暂未收录", 
	"nwinst4.exe": "已知杀软进程,名称暂未收录", 
	"nwservice.exe": "已知杀软进程,名称暂未收录", 
	"nwtool16.exe": "已知杀软进程,名称暂未收录", 
	"ollydbg.exe": "已知杀软进程,名称暂未收录", 
	"onsrvr.exe": "已知杀软进程,名称暂未收录", 
	"optimize.exe": "已知杀软进程,名称暂未收录", 
	"ostronet.exe": "已知杀软进程,名称暂未收录", 
	"outpostproinstall.exe": "已知杀软进程,名称暂未收录", 
	"padmin.exe": "已知杀软进程,名称暂未收录", 
	"panixk.exe": "已知杀软进程,名称暂未收录", 
	"pavcl.exe": "已知杀软进程,名称暂未收录", 
	"pavsched.exe": "已知杀软进程,名称暂未收录", 
	"pccwin98.exe": "已知杀软进程,名称暂未收录", 
	"pcfwallicon.exe": "已知杀软进程,名称暂未收录", 
	"pcip10117_0.exe": "已知杀软进程,名称暂未收录", 
	"periscope.exe": "已知杀软进程,名称暂未收录", 
	"perswf.exe": "已知杀软进程,名称暂未收录", 
	"pf2.exe": "已知杀软进程,名称暂未收录", 
	"pfwadmin.exe": "已知杀软进程,名称暂未收录", 
	"portdetective.exe": "已知杀软进程,名称暂未收录", 
	"portmonitor.exe": "已知杀软进程,名称暂未收录", 
	"procdump.exe": "已知杀软进程,名称暂未收录", 
	"procexplorerv1.0.exe": "已知杀软进程,名称暂未收录", 
	"programauditor.exe": "已知杀软进程,名称暂未收录", 
	"rav7.exe": "已知杀软进程,名称暂未收录", 
	"rav7win.exe": "已知杀软进程,名称暂未收录", 
	"rav8win32eng.exe": "已知杀软进程,名称暂未收录", 
	"ray.exe": "已知杀软进程,名称暂未收录", 
	"reged.exe": "已知杀软进程,名称暂未收录", 
	"regedit.exe": "已知杀软进程,名称暂未收录", 
	"regedt32.exe": "已知杀软进程,名称暂未收录", 
	"rrguard.exe": "已知杀软进程,名称暂未收录", 
	"rundll.exe": "已知杀软进程,名称暂未收录", 
	"rundll16.exe": "已知杀软进程,名称暂未收录", 
	"ruxdll32.exe": "已知杀软进程,名称暂未收录", 
	"sahagent.exescan32.exe": "已知杀软进程,名称暂未收录", 
	"save.exe": "已知杀软进程,名称暂未收录", 
	"savenow.exe": "已知杀软进程,名称暂未收录", 
	"sc.exe": "已知杀软进程,名称暂未收录", 
	"scam32.exe": "已知杀软进程,名称暂未收录", 
	"scan95.exe": "已知杀软进程,名称暂未收录", 
	"scanpm.exe": "已知杀软进程,名称暂未收录", 
	"serv95.exe": "已知杀软进程,名称暂未收录", 
	"setup_flowprotector_us.exe": "已知杀软进程,名称暂未收录", 
	"setupvameeval.exe": "已知杀软进程,名称暂未收录", 
	"sgssfw32.exe": "已知杀软进程,名称暂未收录", 
	"shellspyinstall.exe": "已知杀软进程,名称暂未收录", 
	"shn.exe": "已知杀软进程,名称暂未收录", 
	"smc.exe": "已知杀软进程,名称暂未收录", 
	"sms.exe": "已知杀软进程,名称暂未收录", 
	"smss32.exe": "已知杀软进程,名称暂未收录", 
	"spf.exe": "已知杀软进程,名称暂未收录", 
	"spoler.exe": "已知杀软进程,名称暂未收录", 
	"spoolcv.exe": "已知杀软进程,名称暂未收录", 
	"spoolsv32.exe": "已知杀软进程,名称暂未收录", 
	"spyxx.exe": "已知杀软进程,名称暂未收录", 
	"srexe.exe": "已知杀软进程,名称暂未收录", 
	"srng.exe": "已知杀软进程,名称暂未收录", 
	"ss3edit.exe": "已知杀软进程,名称暂未收录", 
	"ssg_4104.exe": "已知杀软进程,名称暂未收录", 
	"ssgrate.exe": "已知杀软进程,名称暂未收录", 
	"st2.exe": "已知杀软进程,名称暂未收录", 
	"start.exe": "已知杀软进程,名称暂未收录", 
	"stcloader.exe": "已知杀软进程,名称暂未收录", 
	"supftrl.exe": "已知杀软进程,名称暂未收录", 
	"support.exe": "已知杀软进程,名称暂未收录", 
	"svchostc.exe": "已知杀软进程,名称暂未收录", 
	"svchosts.exe": "已知杀软进程,名称暂未收录", 
	"sweep95.exe": "已知杀软进程,名称暂未收录", 
	"sweepnet.sweepsrv.sys.swnetsup.exe": "已知杀软进程,名称暂未收录", 
	"sysedit.exe": "已知杀软进程,名称暂未收录", 
	"sysupd.exe": "已知杀软进程,名称暂未收录", 
	"taskmg.exe": "已知杀软进程,名称暂未收录", 
	"taskmo.exe": "已知杀软进程,名称暂未收录", 
	"taumon.exe": "已知杀软进程,名称暂未收录", 
	"tca.exe": "已知杀软进程,名称暂未收录", 
	"tcm.exe": "已知杀软进程,名称暂未收录", 
	"tds-3.exe": "已知杀软进程,名称暂未收录", 
	"tds2-98.exe": "已知杀软进程,名称暂未收录", 
	"tds2-nt.exe": "已知杀软进程,名称暂未收录", 
	"teekids.exe": "已知杀软进程,名称暂未收录", 
	"tfak.exe": "已知杀软进程,名称暂未收录", 
	"tfak5.exe": "已知杀软进程,名称暂未收录", 
	"tgbob.exe": "已知杀软进程,名称暂未收录", 
	"titaninxp.exe": "已知杀软进程,名称暂未收录", 
	"tracert.exe": "已知杀软进程,名称暂未收录", 
	"trickler.exe": "已知杀软进程,名称暂未收录", 
	"trjscan.exe": "已知杀软进程,名称暂未收录", 
	"trjsetup.exe": "已知杀软进程,名称暂未收录", 
	"trojantrap3.exe": "已知杀软进程,名称暂未收录", 
	"tsadbot.exe": "已知杀软进程,名称暂未收录", 
	"undoboot.exe": "已知杀软进程,名称暂未收录", 
	"updat.exe": "已知杀软进程,名称暂未收录", 
	"update.exe": "已知杀软进程,名称暂未收录", 
	"upgrad.exe": "已知杀软进程,名称暂未收录", 
	"utpost.exe": "已知杀软进程,名称暂未收录", 
	"vbcmserv.exe": "已知杀软进程,名称暂未收录", 
	"vbcons.exe": "已知杀软进程,名称暂未收录", 
	"vbust.exe": "已知杀软进程,名称暂未收录", 
	"vbwin9x.exe": "已知杀软进程,名称暂未收录", 
	"vbwinntw.exe": "已知杀软进程,名称暂未收录", 
	"vcsetup.exe": "已知杀软进程,名称暂未收录", 
	"vet32.exe": "已知杀软进程,名称暂未收录", 
	"vet95.exe": "已知杀软进程,名称暂未收录", 
	"vfsetup.exe": "已知杀软进程,名称暂未收录", 
	"virusmdpersonalfirewall.exe": "已知杀软进程,名称暂未收录", 
	"vnlan300.exe": "已知杀软进程,名称暂未收录", 
	"vpfw30s.exe": "已知杀软进程,名称暂未收录", 
	"vscan40.exe": "已知杀软进程,名称暂未收录", 
	"vscenu6.02d30.exe": "已知杀软进程,名称暂未收录", 
	"vsched.exe": "已知杀软进程,名称暂未收录", 
	"vsecomr.exe": "已知杀软进程,名称暂未收录", 
	"vsisetup.exe": "已知杀软进程,名称暂未收录", 
	"vswin9xe.exe": "已知杀软进程,名称暂未收录", 
	"vswinntse.exe": "已知杀软进程,名称暂未收录", 
	"vswinperse.exe": "已知杀软进程,名称暂未收录", 
	"w32dsm89.exe": "已知杀软进程,名称暂未收录", 
	"w9x.exe": "已知杀软进程,名称暂未收录", 
	"watchdog.exe": "已知杀软进程,名称暂未收录", 
	"webdav.exe": "已知杀软进程,名称暂未收录", 
	"webtrap.exe": "已知杀软进程,名称暂未收录", 
	"whoswatchingme.exe": "已知杀软进程,名称暂未收录", 
	"wimmun32.exe": "已知杀软进程,名称暂未收录", 
	"win-bugsfix.exe": "已知杀软进程,名称暂未收录", 
	"win32.exe": "已知杀软进程,名称暂未收录", 
	"win32us.exe": "已知杀软进程,名称暂未收录", 
	"winactive.exe": "已知杀软进程,名称暂未收录", 
	"window.exe": "已知杀软进程,名称暂未收录", 
	"windows.exe": "已知杀软进程,名称暂未收录", 
	"wininetd.exe": "已知杀软进程,名称暂未收录", 
	"wininitx.exe": "已知杀软进程,名称暂未收录", 
	"winlogin.exe": "已知杀软进程,名称暂未收录", 
	"winmain.exe": "已知杀软进程,名称暂未收录", 
	"winnet.exe": "已知杀软进程,名称暂未收录", 
	"winppr32.exe": "已知杀软进程,名称暂未收录", 
	"winrecon.exe": "已知杀软进程,名称暂未收录", 
	"winservn.exe": "已知杀软进程,名称暂未收录", 
	"winssk32.exe": "已知杀软进程,名称暂未收录", 
	"winstart.exe": "已知杀软进程,名称暂未收录", 
	"winstart001.exe": "已知杀软进程,名称暂未收录", 
	"wintsk32.exe": "已知杀软进程,名称暂未收录", 
	"winupdate.exe": "已知杀软进程,名称暂未收录", 
	"wkufind.exe": "已知杀软进程,名称暂未收录", 
	"wnad.exe": "已知杀软进程,名称暂未收录", 
	"wnt.exe": "已知杀软进程,名称暂未收录", 
	"wradmin.exe": "已知杀软进程,名称暂未收录", 
	"wrctrl.exe": "已知杀软进程,名称暂未收录", 
	"wsbgate.exe": "已知杀软进程,名称暂未收录", 
	"wupdater.exe": "已知杀软进程,名称暂未收录", 
	"wupdt.exe": "已知杀软进程,名称暂未收录", 
	"wyvernworksfirewall.exe": "已知杀软进程,名称暂未收录", 
	"xpf202en.exe": "已知杀软进程,名称暂未收录", 
	"zapsetup3001.exe": "已知杀软进程,名称暂未收录", 
	"zatutor.exe": "已知杀软进程,名称暂未收录", 
	"zonalm2601.exe": "已知杀软进程,名称暂未收录", 
	"AKRNL.exe": "已知杀软进程,名称暂未收录", 
	"TROJAN.exe": "已知杀软进程,名称暂未收录", 
	"ARMOR2NET.exe": "已知杀软进程,名称暂未收录", 
	"ASH.exeexe.exe": "已知杀软进程,名称暂未收录", 
	"ASHENHCD.exe": "已知杀软进程,名称暂未收录", 
	"ASHPOPWZ.exe": "已知杀软进程,名称暂未收录", 
	"ASHSKPCK.exe": "已知杀软进程,名称暂未收录", 
	"AVEVAL.exe": "已知杀软进程,名称暂未收录", 
	"AVGCSRVX.exe": "已知杀软进程,名称暂未收录", 
	"AVKWCTL.exe": "已知杀软进程,名称暂未收录", 
	"AVWUPD32.exe": "已知杀软进程,名称暂未收录", 
	"AVXMONITOR.exe": "已知杀软进程,名称暂未收录", 
	"AVXQUAR.exe": "已知杀软进程,名称暂未收录", 
	"CAFIX.exe": "已知杀软进程,名称暂未收录", 
	"BITDEFENDER.exe": "已知杀软进程,名称暂未收录", 
	"CFPCONFIG.exe": "已知杀软进程,名称暂未收录", 
	"CFIAUDIT.exe": "已知杀软进程,名称暂未收录", 
	"CLAMTRAY.exe": "已知杀软进程,名称暂未收录", 
	"DRVIRUS.exe": "已知杀软进程,名称暂未收录", 
	"DWEBLLIO.exe": "已知杀软进程,名称暂未收录", 
	"DWEBIO.exe": "已知杀软进程,名称暂未收录", 
	"ESCANH95.exe": "已知杀软进程,名称暂未收录", 
	"ESCANHNT.exe": "已知杀软进程,名称暂未收录", 
	"F-AGNT95.exe": "已知杀软进程,名称暂未收录", 
	"FILEMON.exe": "已知杀软进程,名称暂未收录", 
	"FORTICLIENT.exe": "已知杀软进程,名称暂未收录", 
	"FORTISCAN.exe": "已知杀软进程,名称暂未收录", 
	"FPAVSERVER.exe": "已知杀软进程,名称暂未收录", 
	"F-SCHED.exe": "已知杀软进程,名称暂未收录", 
	"FSGUIEXE.exe": "已知杀软进程,名称暂未收录", 
	"FSPEX.exe": "已知杀软进程,名称暂未收录", 
	"F-STOPW.exe": "已知杀软进程,名称暂未收录", 
	"GCASDTSERV.exe": "已知杀软进程,名称暂未收录", 
	"GCASSERV.exe": "已知杀软进程,名称暂未收录", 
	"GIANTANTISPYWARE.exe": "已知杀软进程,名称暂未收录", 
	"GUARDXSERVICE.exe": "已知杀软进程,名称暂未收录", 
	"GUARDXKICKOFF.exe": "已知杀软进程,名称暂未收录", 
	"HREGMON.exe": "已知杀软进程,名称暂未收录", 
	"HRRES.exe": "已知杀软进程,名称暂未收录", 
	"HSOCKPE.exe": "已知杀软进程,名称暂未收录", 
	"HUPDATE.exe": "已知杀软进程,名称暂未收录", 
	"ICLOAD95.exe": "已知杀软进程,名称暂未收录", 
	"ICLOADNT.exe": "已知杀软进程,名称暂未收录", 
	"ICMON.exe": "已知杀软进程,名称暂未收录", 
	"ICSSUPPNT.exe": "已知杀软进程,名称暂未收录", 
	"ICSUPP95.exe": "已知杀软进程,名称暂未收录", 
	"ICSUPPNT.exe": "已知杀软进程,名称暂未收录", 
	"INETUPD.exe": "已知杀软进程,名称暂未收录", 
	"IOMON98.exe": "已知杀软进程,名称暂未收录", 
	"ISATRAY.exe": "已知杀软进程,名称暂未收录", 
	"MAMUTU.exe": "已知杀软进程,名称暂未收录", 
	"NORMIST.exe": "已知杀软进程,名称暂未收录", 
	"NPAVTRAY.exe": "已知杀软进程,名称暂未收录", 
	"NSCHED32.exe": "已知杀软进程,名称暂未收录", 
	"NSSSERV.exe": "已知杀软进程,名称暂未收录", 
	"NSSTRAY.exe": "已知杀软进程,名称暂未收录", 
	"NTOS.exe": "已知杀软进程,名称暂未收录", 
	"NTXCONFIG.exe": "已知杀软进程,名称暂未收录", 
	"NUPGRADE.exe": "已知杀软进程,名称暂未收录", 
	"NVCOD.exe": "已知杀软进程,名称暂未收录", 
	"NVCTE.exe": "已知杀软进程,名称暂未收录", 
	"NVCUT.exe": "已知杀软进程,名称暂未收录", 
	"NWSERVICE.exe": "已知杀软进程,名称暂未收录", 
	"OPSSVC.exe": "已知杀软进程,名称暂未收录", 
	"PERTSK.exe": "已知杀软进程,名称暂未收录", 
	"PNMSRV.exe": "已知杀软进程,名称暂未收录", 
	"PREVX.exe": "已知杀软进程,名称暂未收录", 
	"PSIMSVC.exe": "已知杀软进程,名称暂未收录", 
	"QHONLINE.exe": "已知杀软进程,名称暂未收录", 
	"QHONSVC.exe": "已知杀软进程,名称暂未收录", 
	"QHWSCSVC.exe": "已知杀软进程,名称暂未收录", 
	"QHSET.exe": "已知杀软进程,名称暂未收录", 
	"SALITY.exe": "已知杀软进程,名称暂未收录", 
	"SAPISSVC.exe": "已知杀软进程,名称暂未收录", 
	"SCANWSCS.exe": "已知杀软进程,名称暂未收录", 
	"SCANNINGPROCESS.exe": "已知杀软进程,名称暂未收录", 
	"SDRA64.exe": "已知杀软进程,名称暂未收录", 
	"SITECLI.exe": "已知杀软进程,名称暂未收录", 
	"SPYXX.exe": "已知杀软进程,名称暂未收录", 
	"SS3EDIT.exe": "已知杀软进程,名称暂未收录", 
	"STOPSIGNAV.exe": "已知杀软进程,名称暂未收录", 
	"TAUMON.exe": "已知杀软进程,名称暂未收录", 
	"TRJSCAN.exe": "已知杀软进程,名称暂未收录", 
	"VBA32LDR.exe": "已知杀软进程,名称暂未收录", 
	"VBSNTW.exe": "已知杀软进程,名称暂未收录", 
	"VRFWSVC.exe": "已知杀软进程,名称暂未收录", 
	"VRRW32.exe": "已知杀软进程,名称暂未收录", 
	"VSECOMR.exe": "已知杀软进程,名称暂未收录", 
	"WATCHDOG.exe": "已知杀软进程,名称暂未收录", 
	"WINSSNOTIFY.exe": "已知杀软进程,名称暂未收录", 
	"WRCTRL.exe": "已知杀软进程,名称暂未收录", 
	"ZLCLIENT.exe": "已知杀软进程,名称暂未收录"

};